# Generated by Django 4.2.14 on 2024-07-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sensitivedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensitiveData',
        ),
    ]
